name: CI/CD to Render

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create firebaseKey.json
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" | base64 --decode > firebaseKey.json

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Deploy to Render
        if: success()
        run: |
          curl "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
